name = "VegaLite"
uuid = "112f6efa-9a02-5b7d-90c0-432ed331239a"
version = "3.0.2-DEV"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
NodeJS_16_jll = "a4b94fbf-73f5-58ff-888d-48a8396e17f6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Vega = "239c3e63-733f-47ad-beb7-a12fde22c578"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
FilePaths = "8fc22ac5-c921-52a6-82fd-178b2807b824"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[extras]
VegaDatasets = "0ae4a718-28b7-58ec-9efb-cded64d6d5b4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
TableTraits = "0.3.1, 0.4, 1"
IteratorInterfaceExtensions = "0.1.1, 1"
NodeJS_16_jll = "16"
JSON = "0.19, 0.20, 0.21"
Vega = "2.4"
DataStructures = "0.17, 0.18"
MacroTools = "0.4.4, 0.5"
FileIO = "1.0.1"
TableTraitsUtils = "1"
julia = "1.6"
DataValues = "0.4.4"
FilePaths = "0.7, 0.8"
URIParser = "0.4"

[targets]
test = ["VegaDatasets", "Dates", "Test", "DataFrames", "Setfield", "TestItemRunner"]
